### ISSUE TITLE
What's this array for?

### ISSUE THREAD

**Issue by eggbean** [MrElendig/dotfiles-alice#2]
I think I got directed here through the Arch Wiki as an example of zsh keybindings, but I don't understand what this array is supposed to be for?

https://github.com/MrElendig/dotfiles-alice/blob/ab65a2b951e80aec6950c80b620a85c7d144adab/.zshrc#L42

**Comment by MrElendig** [comment]
just a random leftover from a previous iteration.
As a sidenote: this repo haven't been updated in half a decade so...
